// Generated by uniffi-bindgen-react-native
import installer from './RusaintReactNative';

// Register the rust crate with Hermes
// - the boolean flag ensures this loads exactly once, even if the JS
//   code is reloaded (e.g. during development with metro).
let rustInstalled = false;
if (!rustInstalled) {
  installer.installRustCrate();
  rustInstalled = true;
}

// Export the generated bindings to the app.
export * from './generated/rusaint';
export * from './generated/rusaint_ffi';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as rusaint from './generated/rusaint';
import * as rusaint_ffi from './generated/rusaint_ffi';

// Initialize the generated bindings: mostly checksums, but also callbacks.
// - the boolean flag ensures this loads exactly once, even if the JS code
//   is reloaded (e.g. during development with metro).
let initialized = false;
if (!initialized) {
  rusaint.default.initialize();
  rusaint_ffi.default.initialize();
  initialized = true;
}

// Export the crates as individually namespaced objects.
export default {
  rusaint,
  rusaint_ffi,
};
