// Generated by uniffi-bindgen-react-native
#include "rusaint-react-native.h"
#include "generated/rusaint.hpp"
#include "generated/rusaint_ffi.hpp"

namespace rusaintreactnative {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeRusaint::registerModule(runtime, callInvoker);
		NativeRusaintFfi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}