[bindings.kotlin]
package_name = "dev.eatsteak.rusaint.ffi"
generate_immutable_records = true
android = true

[bindings.swift]
ffi_module_name = "RusaintFFI"
module_name = "Rusaint"
generate_immutable_records = true

[bindings.python]
cdylib_name = "rusaint_ffi"