// Generated by uniffi-bindgen-react-native
package dev.eatsteak.rusaint.reactnative

import android.content.Context
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.annotations.ReactModule
import com.facebook.react.turbomodule.core.interfaces.CallInvokerHolder
import java.util.concurrent.atomic.AtomicBoolean

@ReactModule(name = RusaintReactNativeModule.NAME)
class RusaintReactNativeModule(reactContext: ReactApplicationContext) :
  NativeRusaintReactNativeSpec(reactContext) {

  override fun getName(): String {
    return NAME
  }

  // Two native methods implemented in cpp-adapter.cpp, and ultimately
  // rusaint-react-native.cpp

  external fun nativeInstallRustCrate(runtimePointer: Long, callInvoker: CallInvokerHolder): Boolean
  external fun nativeCleanupRustCrate(runtimePointer: Long): Boolean
  private external fun nativeInitPlatformVerifier(context: Context): Boolean

  override fun installRustCrate(): Boolean {
    val context = this.reactApplicationContext
    ensurePlatformVerifierInitialized(context)
    return nativeInstallRustCrate(
      context.javaScriptContextHolder!!.get(),
      context.jsCallInvokerHolder!!
    )
  }

  private fun ensurePlatformVerifierInitialized(context: ReactApplicationContext) {
    if (verifierInitialized.get()) {
      return
    }

    synchronized(verifierInitialized) {
      if (verifierInitialized.get()) {
        return
      }

      check(nativeInitPlatformVerifier(context.applicationContext)) {
        "Failed to initialize rustls platform verifier"
      }
      verifierInitialized.set(true)
    }
  }

  override fun cleanupRustCrate(): Boolean {
    return nativeCleanupRustCrate(
      this.reactApplicationContext.javaScriptContextHolder!!.get()
    )
  }

  companion object {
    const val NAME = "RusaintReactNative"
    private val verifierInitialized = AtomicBoolean(false)

    init {
      System.loadLibrary("rusaint-react-native")
      System.loadLibrary("rusaint_ffi")
    }
  }
}