// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "rusaint-react-native.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "NativeRusaintReactNativeSpec.h"

@interface RusaintReactNative : NSObject <NativeRusaintReactNativeSpec>
#else
#import <React/RCTBridgeModule.h>

@interface RusaintReactNative : NSObject <RCTBridgeModule>
#endif

@end