# Generated by uniffi-bindgen-react-native
-dontwarn java.awt.*
-keep class com.sun.jna.* { *; }
-keepclassmembers class * extends com.sun.jna.* { public *; }
-keep,includedescriptorclasses class org.rustls.platformverifier.** { *; }
