name: Dry-run before publish

on:
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  dry-run:
    runs-on: ubuntu-latest
    environment: testing
    concurrency:
      group: testing
      cancel-in-progress: true
    env:
      SSO_ID: ${{ vars.SSO_ID }}
      SSO_PASSWORD: ${{ secrets.SSO_PASSWORD }}
      TARGET_YEAR: ${{ vars.TARGET_YEAR }}
      TARGET_SEMESTER: ${{ vars.TARGET_SEMESTER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Retrieve cache
        uses: Leafwing-Studios/cargo-cache@v2
      - name: Publish dry-run
        run: cargo publish -p rusaint --dry-run --verbose
      - name: Run tests
        run: cargo test --verbose
